//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bysj.Domain.Concrete
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BYSJEntities : DbContext
    {
        public BYSJEntities()
            : base("name=BYSJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Steps> Steps { get; set; }
    }
}
