//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bysj.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Steps
    {
        public int id { get; set; }
        public int event_id { get; set; }
        public int staff_id { get; set; }
        public System.DateTime date { get; set; }
        public string notes { get; set; }
        public string situation { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
